name: AdGuard Home Proxy
version: "0.2"
panel_icon: "mdi:shield-check"
panel_title: AdGuard Home
slug: adguard-proxy
description: Proxy addon Network-wide ads & trackers blocking DNS server
url: "https://github.com/kitchung/hassio-addons/adguard_proxy"
startup: application
boot: auto
#webui: "http://[HOST]:[PORT:3000]/"
#watchdog: "http://[HOST]:[PORT:3000]/"
ingress: true
ingress_port: 3000
ingress_entry: /
panel_admin: false
#ports:
#  3000/tcp: 3000
#ports_description:
#  5000/tcp: Web interface (Not required for Hass.io Ingress)
host_network: false
devices: []
usb: false
tmpfs: false
full_access: false
environment: {}
options:
  server: "adguard.local:3000"
schema:
  server: "match(^.+:\\d+$)"
services: []
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map: []
