{
  "name": "AdGuard Home Proxy",
  "version": "0.4",
  "url": "https://github.com/kitchung/hassio-addons/adguard_proxy",
  "panel_icon": "mdi:shield-check",
  "slug": "adguard-proxy",
  "description": "Proxy addon Network-wide ads & trackers blocking DNS server",
  "arch": ["aarch64", "amd64", "armhf", "armv7", "i386"],
  "startup": "application",
  "boot": "auto",
  "ingress": true,
  "ingress_port": 3000,
  "panel_admin": false,
  "options": {
    "server": "adguard-home.local:3000"
  },
  "schema": {
    "server": "match(^.+:\\d+$)"
  }
}
